openapi: 3.0.3
info:
  title: 'Api Documentation for Ifiag'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8001'
paths:
  /api/register:
    post:
      summary: 'Api for register'
      operationId: apiForRegister
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Compte créé'
                  access_token: ohrpohjo
                  token_type: Bearer
                  expired_at: '2023-04-04'
                properties:
                  message:
                    type: string
                    example: 'Compte créé'
                  access_token:
                    type: string
                    example: ohrpohjo
                  token_type:
                    type: string
                    example: Bearer
                  expired_at:
                    type: string
                    example: '2023-04-04'
      tags:
        - 'API Authentification'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'required. The name of the user.Example : John Doe'
                  example: dolorem
                email:
                  type: string
                  description: 'required. The email of the user.'
                  example: john@doe.com
                password:
                  type: string
                  description: 'min:6.'
                  example: '123456'
              required:
                - password
      security: []
  /api/test-api:
    get:
      summary: ''
      operationId: getApiTestApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Bonjour à tous'
                properties:
                  message:
                    type: string
                    example: 'Bonjour à tous'
      tags:
        - Endpoints
      security: []
  /api/not-login-api:
    get:
      summary: ''
      operationId: getApiNotLoginApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not authenticated'
                properties:
                  message:
                    type: string
                    example: 'User not authenticated'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: 'API Authentification'
    description: ''
  -
    name: Endpoints
    description: ''
